import Link from "next/link"
import './global.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <nav> 
          <Link href='/'>Home</Link>
          <Link href='/notes'>Notes</Link>
        </nav>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
